import type { Metadata } from "next";
import "../styles/globals.css";

import Client from "./client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return <Client>{children}</Client>;
}
